<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gaming Haven</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Welcome to Gaming Haven</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Reviews</a></li>
                <li><a href="#">News</a></li>
                <li><a href="#">Tutorials</a></li>
                <li><a href="#">Forums</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <section>
            <h2>Latest Reviews</h2>
            <article>
                <h3>Game Title 1</h3>
                <p>Review content goes here...</p>
            </article>
            <article>
                <h3>Game Title 2</h3>
                <p>Review content goes here...</p>
            </article>
        </section>
        <section>
            <h2>Game News</h2>
            <article>
                <h3>News Title 1</h3>
                <p>News content goes here...</p>
            </article>
            <article>
                <h3>News Title 2</h3>
                <p>News content goes here...</p>
            </article>
        </section>
    </main>
    <footer>
        <p>&copy; 2025 Gaming Haven. All rights reserved.</p>
    </footer>
</body>
</html>
body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background-color: #f4f4f4;
}

header {
    background-color: #333;
    color: #fff;
    padding: 1em 0;
    text-align: center;
}

nav ul {
    list-style-type: none;
    padding: 0;
}

nav ul li {
    display: inline;
    margin: 0 10px;
}

nav ul li a {
    color: #fff;
    text-decoration: none;
}

main {
    padding: 20px;
}

section {
    margin-bottom: 20px;
}

h2 {
    color: #333;
}

article {
    background-color: #fff;
    padding: 15px;
    margin-bottom: 10px;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

footer {
    background-color: #333;
    color: #fff;
    text-align: center;
    padding: 10px 0;
    position: fixed;
    width: 100%;
    bottom: 0;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gaming Haven</title>
    <link rel="stylesheet" href="styles.css">
    <script src="scripts.js" defer></script>
</head>
<body>
    <!-- ... existing HTML content ... -->
    <footer>
        <p>&copy; <span id="year"></span> Gaming Haven. All rights reserved.</p>
    </footer>
</body>
</html>
document.addEventListener("DOMContentLoaded", function() {
    const yearSpan = document.getElementById("year");
    const currentYear = new Date().getFullYear();
    yearSpan.textContent = currentYear;
});
